# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(789, 699)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralWidget.sizePolicy().hasHeightForWidth())
        self.centralWidget.setSizePolicy(sizePolicy)
        self.centralWidget.setObjectName("centralWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralWidget)
        self.verticalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.scrollArea = QtWidgets.QScrollArea(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 754, 765))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollAreaWidgetContents.sizePolicy().hasHeightForWidth())
        self.scrollAreaWidgetContents.setSizePolicy(sizePolicy)
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.scrollAreaWidgetContents)
        self.horizontalLayout_6.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_6.setSpacing(6)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.widget = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setContentsMargins(11, 11, 11, 11)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.frame_2 = QtWidgets.QFrame(self.widget)
        self.frame_2.setFocusPolicy(QtCore.Qt.NoFocus)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_4.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_4.setSpacing(6)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.widget_4 = QtWidgets.QWidget(self.frame_2)
        self.widget_4.setObjectName("widget_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget_4)
        self.verticalLayout_4.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_4.setSpacing(6)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.npToolButton = QtWidgets.QToolButton(self.widget_4)
        self.npToolButton.setEnabled(True)
        self.npToolButton.setAutoRaise(False)
        self.npToolButton.setArrowType(QtCore.Qt.DownArrow)
        self.npToolButton.setObjectName("npToolButton")
        self.verticalLayout_4.addWidget(self.npToolButton)
        spacerItem = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem)
        self.horizontalLayout_4.addWidget(self.widget_4)
        self.groupBox = QtWidgets.QGroupBox(self.frame_2)
        self.groupBox.setAutoFillBackground(True)
        self.groupBox.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.groupBox.setFlat(False)
        self.groupBox.setCheckable(False)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_2.setSpacing(6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.npWidget = QtWidgets.QWidget(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.npWidget.sizePolicy().hasHeightForWidth())
        self.npWidget.setSizePolicy(sizePolicy)
        self.npWidget.setObjectName("npWidget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.npWidget)
        self.gridLayout_4.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_4.setSpacing(6)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_4 = QtWidgets.QLabel(self.npWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout_4.addWidget(self.label_4, 1, 0, 1, 1)
        self.npStartBoundaryY = QtWidgets.QLineEdit(self.npWidget)
        self.npStartBoundaryY.setMaximumSize(QtCore.QSize(50, 16777215))
        self.npStartBoundaryY.setObjectName("npStartBoundaryY")
        self.gridLayout_4.addWidget(self.npStartBoundaryY, 1, 2, 1, 1)
        self.npStopBoundaryX = QtWidgets.QLineEdit(self.npWidget)
        self.npStopBoundaryX.setMaximumSize(QtCore.QSize(50, 16777215))
        self.npStopBoundaryX.setObjectName("npStopBoundaryX")
        self.gridLayout_4.addWidget(self.npStopBoundaryX, 2, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.npWidget)
        self.label_6.setObjectName("label_6")
        self.gridLayout_4.addWidget(self.label_6, 2, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.npWidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout_4.addWidget(self.label_5, 3, 0, 1, 1)
        self.npResolutionX = QtWidgets.QLineEdit(self.npWidget)
        self.npResolutionX.setMaximumSize(QtCore.QSize(50, 16777215))
        self.npResolutionX.setObjectName("npResolutionX")
        self.gridLayout_4.addWidget(self.npResolutionX, 3, 1, 1, 1)
        self.npTolerance = QtWidgets.QLineEdit(self.npWidget)
        self.npTolerance.setMaximumSize(QtCore.QSize(50, 16777215))
        self.npTolerance.setObjectName("npTolerance")
        self.gridLayout_4.addWidget(self.npTolerance, 4, 1, 1, 1)
        self.npResolutionY = QtWidgets.QLineEdit(self.npWidget)
        self.npResolutionY.setMaximumSize(QtCore.QSize(50, 16777215))
        self.npResolutionY.setObjectName("npResolutionY")
        self.gridLayout_4.addWidget(self.npResolutionY, 3, 2, 1, 1)
        self.label = QtWidgets.QLabel(self.npWidget)
        self.label.setObjectName("label")
        self.gridLayout_4.addWidget(self.label, 4, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.npWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout_4.addWidget(self.label_2, 0, 0, 1, 1)
        self.npStopBoundaryY = QtWidgets.QLineEdit(self.npWidget)
        self.npStopBoundaryY.setMaximumSize(QtCore.QSize(50, 16777215))
        self.npStopBoundaryY.setObjectName("npStopBoundaryY")
        self.gridLayout_4.addWidget(self.npStopBoundaryY, 2, 2, 1, 1)
        self.npStartingPointX = QtWidgets.QLineEdit(self.npWidget)
        self.npStartingPointX.setMaximumSize(QtCore.QSize(50, 16777215))
        self.npStartingPointX.setObjectName("npStartingPointX")
        self.gridLayout_4.addWidget(self.npStartingPointX, 0, 1, 1, 1)
        self.npStartingPointY = QtWidgets.QLineEdit(self.npWidget)
        self.npStartingPointY.setMaximumSize(QtCore.QSize(50, 16777215))
        self.npStartingPointY.setObjectName("npStartingPointY")
        self.gridLayout_4.addWidget(self.npStartingPointY, 0, 2, 1, 1)
        self.npStartBoundaryX = QtWidgets.QLineEdit(self.npWidget)
        self.npStartBoundaryX.setMaximumSize(QtCore.QSize(50, 16777215))
        self.npStartBoundaryX.setObjectName("npStartBoundaryX")
        self.gridLayout_4.addWidget(self.npStartBoundaryX, 1, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem1, 0, 3, 1, 1)
        self.gridLayout_2.addWidget(self.npWidget, 0, 0, 1, 1)
        self.horizontalLayout_4.addWidget(self.groupBox)
        spacerItem2 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.gridLayout.addWidget(self.frame_2, 3, 0, 1, 2)
        self.frame = QtWidgets.QFrame(self.widget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_5.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_5.setSpacing(6)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.widget_6 = QtWidgets.QWidget(self.frame)
        self.widget_6.setObjectName("widget_6")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.widget_6)
        self.verticalLayout_5.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_5.setSpacing(6)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.dpToolButton = QtWidgets.QToolButton(self.widget_6)
        self.dpToolButton.setArrowType(QtCore.Qt.DownArrow)
        self.dpToolButton.setObjectName("dpToolButton")
        self.verticalLayout_5.addWidget(self.dpToolButton)
        spacerItem3 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem3)
        self.horizontalLayout_5.addWidget(self.widget_6)
        self.groupBox_3 = QtWidgets.QGroupBox(self.frame)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_3.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_3.setSpacing(6)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.dpWidget = QtWidgets.QWidget(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dpWidget.sizePolicy().hasHeightForWidth())
        self.dpWidget.setSizePolicy(sizePolicy)
        self.dpWidget.setObjectName("dpWidget")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.dpWidget)
        self.gridLayout_5.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_5.setSpacing(6)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_3 = QtWidgets.QLabel(self.dpWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout_5.addWidget(self.label_3, 0, 0, 1, 1)
        self.dpStartBoundaryY = QtWidgets.QLineEdit(self.dpWidget)
        self.dpStartBoundaryY.setMaximumSize(QtCore.QSize(50, 16777215))
        self.dpStartBoundaryY.setObjectName("dpStartBoundaryY")
        self.gridLayout_5.addWidget(self.dpStartBoundaryY, 0, 2, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem4, 0, 3, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.dpWidget)
        self.label_7.setObjectName("label_7")
        self.gridLayout_5.addWidget(self.label_7, 1, 0, 1, 1)
        self.dpStartBoundaryX = QtWidgets.QLineEdit(self.dpWidget)
        self.dpStartBoundaryX.setMaximumSize(QtCore.QSize(50, 16777215))
        self.dpStartBoundaryX.setObjectName("dpStartBoundaryX")
        self.gridLayout_5.addWidget(self.dpStartBoundaryX, 0, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.dpWidget)
        self.label_8.setObjectName("label_8")
        self.gridLayout_5.addWidget(self.label_8, 2, 0, 1, 1)
        self.dpStopBoundaryX = QtWidgets.QLineEdit(self.dpWidget)
        self.dpStopBoundaryX.setMaximumSize(QtCore.QSize(50, 16777215))
        self.dpStopBoundaryX.setObjectName("dpStopBoundaryX")
        self.gridLayout_5.addWidget(self.dpStopBoundaryX, 1, 1, 1, 1)
        self.dpStopBoundaryY = QtWidgets.QLineEdit(self.dpWidget)
        self.dpStopBoundaryY.setMaximumSize(QtCore.QSize(50, 16777215))
        self.dpStopBoundaryY.setObjectName("dpStopBoundaryY")
        self.gridLayout_5.addWidget(self.dpStopBoundaryY, 1, 2, 1, 1)
        self.dpResolutionX = QtWidgets.QLineEdit(self.dpWidget)
        self.dpResolutionX.setMaximumSize(QtCore.QSize(50, 16777215))
        self.dpResolutionX.setObjectName("dpResolutionX")
        self.gridLayout_5.addWidget(self.dpResolutionX, 2, 1, 1, 1)
        self.dpResolutionY = QtWidgets.QLineEdit(self.dpWidget)
        self.dpResolutionY.setMaximumSize(QtCore.QSize(50, 16777215))
        self.dpResolutionY.setObjectName("dpResolutionY")
        self.gridLayout_5.addWidget(self.dpResolutionY, 2, 2, 1, 1)
        self.gridLayout_3.addWidget(self.dpWidget, 0, 0, 1, 1)
        self.horizontalLayout_5.addWidget(self.groupBox_3)
        spacerItem5 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem5)
        self.gridLayout.addWidget(self.frame, 4, 0, 1, 2)
        self.groupBox_2 = QtWidgets.QGroupBox(self.widget)
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_7.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_7.setSpacing(6)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.formulaInput = QtWidgets.QLineEdit(self.groupBox_2)
        self.formulaInput.setMinimumSize(QtCore.QSize(350, 0))
        self.formulaInput.setObjectName("formulaInput")
        self.horizontalLayout_7.addWidget(self.formulaInput)
        self.executeButton = QtWidgets.QPushButton(self.groupBox_2)
        self.executeButton.setObjectName("executeButton")
        self.horizontalLayout_7.addWidget(self.executeButton)
        self.gridLayout.addWidget(self.groupBox_2, 0, 0, 1, 1)
        self.horizontalLayout_2.addLayout(self.gridLayout)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.tabWidget = QtWidgets.QTabWidget(self.widget)
        self.tabWidget.setObjectName("tabWidget")
        self.resultTab = QtWidgets.QWidget()
        self.resultTab.setObjectName("resultTab")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.resultTab)
        self.horizontalLayout.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.resultTextArea = QtWidgets.QTextEdit(self.resultTab)
        self.resultTextArea.setObjectName("resultTextArea")
        self.horizontalLayout.addWidget(self.resultTextArea)
        self.tabWidget.addTab(self.resultTab, "")
        self.consoleTab = QtWidgets.QWidget()
        self.consoleTab.setObjectName("consoleTab")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.consoleTab)
        self.horizontalLayout_3.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.consoleTextArea = QtWidgets.QTextEdit(self.consoleTab)
        self.consoleTextArea.setObjectName("consoleTextArea")
        self.horizontalLayout_3.addWidget(self.consoleTextArea)
        self.tabWidget.addTab(self.consoleTab, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.tabWidget.raise_()
        self.horizontalLayout_6.addWidget(self.widget)
        self.widget_2 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_2.sizePolicy().hasHeightForWidth())
        self.widget_2.setSizePolicy(sizePolicy)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout_8.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_8.setSpacing(6)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.plotterTabWidget = QtWidgets.QTabWidget(self.widget_2)
        self.plotterTabWidget.setObjectName("plotterTabWidget")
        self.plotAllTab = QtWidgets.QWidget()
        self.plotAllTab.setObjectName("plotAllTab")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.plotAllTab)
        self.horizontalLayout_9.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_9.setSpacing(6)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.plotAllLayout = QtWidgets.QVBoxLayout()
        self.plotAllLayout.setContentsMargins(11, 11, 11, 11)
        self.plotAllLayout.setSpacing(6)
        self.plotAllLayout.setObjectName("plotAllLayout")
        self.horizontalLayout_9.addLayout(self.plotAllLayout)
        self.plotterTabWidget.addTab(self.plotAllTab, "")
        self.plot3dTab = QtWidgets.QWidget()
        self.plot3dTab.setObjectName("plot3dTab")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.plot3dTab)
        self.verticalLayout_8.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_8.setSpacing(6)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.plot3dLayout = QtWidgets.QVBoxLayout()
        self.plot3dLayout.setContentsMargins(11, 11, 11, 11)
        self.plot3dLayout.setSpacing(6)
        self.plot3dLayout.setObjectName("plot3dLayout")
        self.verticalLayout_8.addLayout(self.plot3dLayout)
        self.plotterTabWidget.addTab(self.plot3dTab, "")
        self.plotMeshgridTab = QtWidgets.QWidget()
        self.plotMeshgridTab.setObjectName("plotMeshgridTab")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.plotMeshgridTab)
        self.verticalLayout_9.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_9.setSpacing(6)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.plotMeshgridLayout = QtWidgets.QVBoxLayout()
        self.plotMeshgridLayout.setContentsMargins(11, 11, 11, 11)
        self.plotMeshgridLayout.setSpacing(6)
        self.plotMeshgridLayout.setObjectName("plotMeshgridLayout")
        self.verticalLayout_9.addLayout(self.plotMeshgridLayout)
        self.plotterTabWidget.addTab(self.plotMeshgridTab, "")
        self.horizontalLayout_8.addWidget(self.plotterTabWidget)
        self.horizontalLayout_6.addWidget(self.widget_2)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_2.addWidget(self.scrollArea)
        MainWindow.setCentralWidget(self.centralWidget)
        self.mainToolBar = QtWidgets.QToolBar(MainWindow)
        self.mainToolBar.setObjectName("mainToolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 789, 27))
        self.menuBar.setObjectName("menuBar")
        self.menuChoose_function = QtWidgets.QMenu(self.menuBar)
        self.menuChoose_function.setObjectName("menuChoose_function")
        MainWindow.setMenuBar(self.menuBar)
        self.actionAckley_s = QtWidgets.QAction(MainWindow)
        self.actionAckley_s.setObjectName("actionAckley_s")
        self.actionSphere = QtWidgets.QAction(MainWindow)
        self.actionSphere.setObjectName("actionSphere")
        self.actionRosenbrock = QtWidgets.QAction(MainWindow)
        self.actionRosenbrock.setObjectName("actionRosenbrock")
        self.actionBeale_s = QtWidgets.QAction(MainWindow)
        self.actionBeale_s.setObjectName("actionBeale_s")
        self.actionGoldstein_Price = QtWidgets.QAction(MainWindow)
        self.actionGoldstein_Price.setObjectName("actionGoldstein_Price")
        self.actionBooth_s = QtWidgets.QAction(MainWindow)
        self.actionBooth_s.setObjectName("actionBooth_s")
        self.actionBukin = QtWidgets.QAction(MainWindow)
        self.actionBukin.setObjectName("actionBukin")
        self.actionMatyas = QtWidgets.QAction(MainWindow)
        self.actionMatyas.setObjectName("actionMatyas")
        self.actionLevi = QtWidgets.QAction(MainWindow)
        self.actionLevi.setObjectName("actionLevi")
        self.actionEasom = QtWidgets.QAction(MainWindow)
        self.actionEasom.setObjectName("actionEasom")
        self.actionCross_in_tray = QtWidgets.QAction(MainWindow)
        self.actionCross_in_tray.setObjectName("actionCross_in_tray")
        self.actionEggholder = QtWidgets.QAction(MainWindow)
        self.actionEggholder.setObjectName("actionEggholder")
        self.actionHolder = QtWidgets.QAction(MainWindow)
        self.actionHolder.setObjectName("actionHolder")
        self.actionStyblinski_Tang = QtWidgets.QAction(MainWindow)
        self.actionStyblinski_Tang.setObjectName("actionStyblinski_Tang")
        self.actionSimionescu = QtWidgets.QAction(MainWindow)
        self.actionSimionescu.setObjectName("actionSimionescu")
        self.actionSchaffer = QtWidgets.QAction(MainWindow)
        self.actionSchaffer.setObjectName("actionSchaffer")
        self.menuChoose_function.addAction(self.actionAckley_s)
        self.menuChoose_function.addAction(self.actionSphere)
        self.menuChoose_function.addAction(self.actionRosenbrock)
        self.menuChoose_function.addAction(self.actionBeale_s)
        self.menuChoose_function.addAction(self.actionGoldstein_Price)
        self.menuChoose_function.addAction(self.actionBooth_s)
        self.menuChoose_function.addAction(self.actionBukin)
        self.menuChoose_function.addAction(self.actionMatyas)
        self.menuChoose_function.addAction(self.actionLevi)
        self.menuChoose_function.addAction(self.actionEasom)
        self.menuChoose_function.addAction(self.actionCross_in_tray)
        self.menuChoose_function.addAction(self.actionEggholder)
        self.menuChoose_function.addAction(self.actionHolder)
        self.menuChoose_function.addAction(self.actionStyblinski_Tang)
        self.menuChoose_function.addAction(self.actionSimionescu)
        self.menuChoose_function.addAction(self.actionSchaffer)
        self.menuBar.addAction(self.menuChoose_function.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.plotterTabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Newton Optimization"))
        self.npToolButton.setText(_translate("MainWindow", "..."))
        self.groupBox.setTitle(_translate("MainWindow", "Newton parameters", "asfdasdf"))
        self.label_4.setText(_translate("MainWindow", "Start boundary X, Y:"))
        self.npStartBoundaryY.setText(_translate("MainWindow", "-4"))
        self.npStopBoundaryX.setText(_translate("MainWindow", "4"))
        self.label_6.setText(_translate("MainWindow", "Stop boundary X, Y:"))
        self.label_5.setText(_translate("MainWindow", "Resolution X, Y:"))
        self.npResolutionX.setText(_translate("MainWindow", "0.01"))
        self.npTolerance.setText(_translate("MainWindow", "0.01"))
        self.npResolutionY.setText(_translate("MainWindow", "0.01"))
        self.label.setText(_translate("MainWindow", "Tolerance"))
        self.label_2.setText(_translate("MainWindow", "Starting point X, Y:"))
        self.npStopBoundaryY.setText(_translate("MainWindow", "4"))
        self.npStartingPointX.setText(_translate("MainWindow", "1"))
        self.npStartingPointY.setText(_translate("MainWindow", "1"))
        self.npStartBoundaryX.setText(_translate("MainWindow", "-4"))
        self.dpToolButton.setText(_translate("MainWindow", "..."))
        self.groupBox_3.setTitle(_translate("MainWindow", "Drawing parameters"))
        self.label_3.setText(_translate("MainWindow", "Start boundary X, Y:"))
        self.dpStartBoundaryY.setText(_translate("MainWindow", "-4"))
        self.label_7.setText(_translate("MainWindow", "Stop boundary X, Y:"))
        self.dpStartBoundaryX.setText(_translate("MainWindow", "-4"))
        self.label_8.setText(_translate("MainWindow", "Resolution X, Y:"))
        self.dpStopBoundaryX.setText(_translate("MainWindow", "4"))
        self.dpStopBoundaryY.setText(_translate("MainWindow", "4"))
        self.dpResolutionX.setText(_translate("MainWindow", "0.5"))
        self.dpResolutionY.setText(_translate("MainWindow", "0.5"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Goal function"))
        self.formulaInput.setText(_translate("MainWindow", "x ^ 4 * (y - 1) ^ 2  + y ^ 4 * (x - 1) ^ 2"))
        self.executeButton.setText(_translate("MainWindow", "Execute"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.resultTab), _translate("MainWindow", "Result"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.consoleTab), _translate("MainWindow", "Console"))
        self.plotterTabWidget.setTabText(self.plotterTabWidget.indexOf(self.plotAllTab), _translate("MainWindow", "All"))
        self.plotterTabWidget.setTabText(self.plotterTabWidget.indexOf(self.plot3dTab), _translate("MainWindow", "3D plot"))
        self.plotterTabWidget.setTabText(self.plotterTabWidget.indexOf(self.plotMeshgridTab), _translate("MainWindow", "Meshgrid"))
        self.menuChoose_function.setTitle(_translate("MainWindow", "Choose function"))
        self.actionAckley_s.setText(_translate("MainWindow", "Ackley\'s"))
        self.actionSphere.setText(_translate("MainWindow", "Sphere"))
        self.actionRosenbrock.setText(_translate("MainWindow", "Rosenbrock"))
        self.actionBeale_s.setText(_translate("MainWindow", "Beale\'s"))
        self.actionGoldstein_Price.setText(_translate("MainWindow", "Goldstein-Price"))
        self.actionBooth_s.setText(_translate("MainWindow", "Booth\'s"))
        self.actionBukin.setText(_translate("MainWindow", "Bukin"))
        self.actionMatyas.setText(_translate("MainWindow", "Matyas"))
        self.actionLevi.setText(_translate("MainWindow", "Levi"))
        self.actionEasom.setText(_translate("MainWindow", "Easom"))
        self.actionCross_in_tray.setText(_translate("MainWindow", "Cross-in-tray"))
        self.actionEggholder.setText(_translate("MainWindow", "Eggholder"))
        self.actionHolder.setText(_translate("MainWindow", "Hölder"))
        self.actionStyblinski_Tang.setText(_translate("MainWindow", "Styblinski-Tang"))
        self.actionSimionescu.setText(_translate("MainWindow", "Simionescu"))
        self.actionSchaffer.setText(_translate("MainWindow", "Schaffer"))

