# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(728, 699)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralWidget)
        self.verticalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setContentsMargins(11, 11, 11, 11)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.frame_2 = QtWidgets.QFrame(self.centralWidget)
        self.frame_2.setFocusPolicy(QtCore.Qt.NoFocus)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_4.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_4.setSpacing(6)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.groupBox = QtWidgets.QGroupBox(self.frame_2)
        self.groupBox.setAutoFillBackground(True)
        self.groupBox.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.groupBox.setFlat(False)
        self.groupBox.setCheckable(False)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_2.setSpacing(6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.npStartingPointY = QtWidgets.QLineEdit(self.groupBox)
        self.npStartingPointY.setMaximumSize(QtCore.QSize(50, 16777215))
        self.npStartingPointY.setObjectName("npStartingPointY")
        self.gridLayout_2.addWidget(self.npStartingPointY, 0, 2, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 2, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 3, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 0, 3, 1, 1)
        self.npStartingPointX = QtWidgets.QLineEdit(self.groupBox)
        self.npStartingPointX.setMaximumSize(QtCore.QSize(50, 16777215))
        self.npStartingPointX.setObjectName("npStartingPointX")
        self.gridLayout_2.addWidget(self.npStartingPointX, 0, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 1, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 4, 0, 1, 1)
        self.npStartBoundaryX = QtWidgets.QLineEdit(self.groupBox)
        self.npStartBoundaryX.setMaximumSize(QtCore.QSize(50, 16777215))
        self.npStartBoundaryX.setObjectName("npStartBoundaryX")
        self.gridLayout_2.addWidget(self.npStartBoundaryX, 1, 1, 1, 1)
        self.npStartBoundaryY = QtWidgets.QLineEdit(self.groupBox)
        self.npStartBoundaryY.setMaximumSize(QtCore.QSize(50, 16777215))
        self.npStartBoundaryY.setObjectName("npStartBoundaryY")
        self.gridLayout_2.addWidget(self.npStartBoundaryY, 1, 2, 1, 1)
        self.npStopBoundaryX = QtWidgets.QLineEdit(self.groupBox)
        self.npStopBoundaryX.setMaximumSize(QtCore.QSize(50, 16777215))
        self.npStopBoundaryX.setObjectName("npStopBoundaryX")
        self.gridLayout_2.addWidget(self.npStopBoundaryX, 2, 1, 1, 1)
        self.npStopBoundaryY = QtWidgets.QLineEdit(self.groupBox)
        self.npStopBoundaryY.setMaximumSize(QtCore.QSize(50, 16777215))
        self.npStopBoundaryY.setObjectName("npStopBoundaryY")
        self.gridLayout_2.addWidget(self.npStopBoundaryY, 2, 2, 1, 1)
        self.npResolutionX = QtWidgets.QLineEdit(self.groupBox)
        self.npResolutionX.setMaximumSize(QtCore.QSize(50, 16777215))
        self.npResolutionX.setObjectName("npResolutionX")
        self.gridLayout_2.addWidget(self.npResolutionX, 3, 1, 1, 1)
        self.npResolutionY = QtWidgets.QLineEdit(self.groupBox)
        self.npResolutionY.setMaximumSize(QtCore.QSize(50, 16777215))
        self.npResolutionY.setObjectName("npResolutionY")
        self.gridLayout_2.addWidget(self.npResolutionY, 3, 2, 1, 1)
        self.npTolerance = QtWidgets.QLineEdit(self.groupBox)
        self.npTolerance.setMaximumSize(QtCore.QSize(50, 16777215))
        self.npTolerance.setObjectName("npTolerance")
        self.gridLayout_2.addWidget(self.npTolerance, 4, 1, 1, 1)
        self.horizontalLayout_4.addWidget(self.groupBox)
        self.gridLayout.addWidget(self.frame_2, 3, 0, 1, 2)
        self.frame = QtWidgets.QFrame(self.centralWidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_5.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_5.setSpacing(6)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.groupBox_3 = QtWidgets.QGroupBox(self.frame)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_3.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_3.setSpacing(6)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_3 = QtWidgets.QLabel(self.groupBox_3)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 0, 0, 1, 1)
        self.dpStartBoundaryX = QtWidgets.QLineEdit(self.groupBox_3)
        self.dpStartBoundaryX.setMaximumSize(QtCore.QSize(50, 16777215))
        self.dpStartBoundaryX.setObjectName("dpStartBoundaryX")
        self.gridLayout_3.addWidget(self.dpStartBoundaryX, 0, 1, 1, 1)
        self.dpStartBoundaryY = QtWidgets.QLineEdit(self.groupBox_3)
        self.dpStartBoundaryY.setMaximumSize(QtCore.QSize(50, 16777215))
        self.dpStartBoundaryY.setObjectName("dpStartBoundaryY")
        self.gridLayout_3.addWidget(self.dpStartBoundaryY, 0, 2, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem1, 0, 3, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.groupBox_3)
        self.label_7.setObjectName("label_7")
        self.gridLayout_3.addWidget(self.label_7, 1, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.groupBox_3)
        self.label_8.setObjectName("label_8")
        self.gridLayout_3.addWidget(self.label_8, 2, 0, 1, 1)
        self.dpStopBoundaryX = QtWidgets.QLineEdit(self.groupBox_3)
        self.dpStopBoundaryX.setMaximumSize(QtCore.QSize(50, 16777215))
        self.dpStopBoundaryX.setObjectName("dpStopBoundaryX")
        self.gridLayout_3.addWidget(self.dpStopBoundaryX, 1, 1, 1, 1)
        self.dpStopBoundaryY = QtWidgets.QLineEdit(self.groupBox_3)
        self.dpStopBoundaryY.setMaximumSize(QtCore.QSize(50, 16777215))
        self.dpStopBoundaryY.setObjectName("dpStopBoundaryY")
        self.gridLayout_3.addWidget(self.dpStopBoundaryY, 1, 2, 1, 1)
        self.dpResolutionX = QtWidgets.QLineEdit(self.groupBox_3)
        self.dpResolutionX.setMaximumSize(QtCore.QSize(50, 16777215))
        self.dpResolutionX.setObjectName("dpResolutionX")
        self.gridLayout_3.addWidget(self.dpResolutionX, 2, 1, 1, 1)
        self.dpResolutionY = QtWidgets.QLineEdit(self.groupBox_3)
        self.dpResolutionY.setMaximumSize(QtCore.QSize(50, 16777215))
        self.dpResolutionY.setObjectName("dpResolutionY")
        self.gridLayout_3.addWidget(self.dpResolutionY, 2, 2, 1, 1)
        self.horizontalLayout_5.addWidget(self.groupBox_3)
        self.gridLayout.addWidget(self.frame, 4, 0, 1, 2)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralWidget)
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_7.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_7.setSpacing(6)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.formulaInput = QtWidgets.QLineEdit(self.groupBox_2)
        self.formulaInput.setObjectName("formulaInput")
        self.horizontalLayout_7.addWidget(self.formulaInput)
        self.executeButton = QtWidgets.QPushButton(self.groupBox_2)
        self.executeButton.setObjectName("executeButton")
        self.horizontalLayout_7.addWidget(self.executeButton)
        self.gridLayout.addWidget(self.groupBox_2, 0, 0, 1, 1)
        self.horizontalLayout_2.addLayout(self.gridLayout)
        self.matPlotLayout = QtWidgets.QVBoxLayout()
        self.matPlotLayout.setContentsMargins(11, 11, 11, 11)
        self.matPlotLayout.setSpacing(6)
        self.matPlotLayout.setObjectName("matPlotLayout")
        self.horizontalLayout_2.addLayout(self.matPlotLayout)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.tabWidget = QtWidgets.QTabWidget(self.centralWidget)
        self.tabWidget.setObjectName("tabWidget")
        self.resultTab = QtWidgets.QWidget()
        self.resultTab.setObjectName("resultTab")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.resultTab)
        self.horizontalLayout.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.resultTextArea = QtWidgets.QTextEdit(self.resultTab)
        self.resultTextArea.setObjectName("resultTextArea")
        self.horizontalLayout.addWidget(self.resultTextArea)
        self.tabWidget.addTab(self.resultTab, "")
        self.consoleTab = QtWidgets.QWidget()
        self.consoleTab.setObjectName("consoleTab")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.consoleTab)
        self.horizontalLayout_3.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.consoleTextArea = QtWidgets.QTextEdit(self.consoleTab)
        self.consoleTextArea.setObjectName("consoleTextArea")
        self.horizontalLayout_3.addWidget(self.consoleTextArea)
        self.tabWidget.addTab(self.consoleTab, "")
        self.verticalLayout_2.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralWidget)
        self.mainToolBar = QtWidgets.QToolBar(MainWindow)
        self.mainToolBar.setObjectName("mainToolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 728, 23))
        self.menuBar.setObjectName("menuBar")
        MainWindow.setMenuBar(self.menuBar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Newton Optimization"))
        self.groupBox.setTitle(_translate("MainWindow", "Newton parameters", "asfdasdf"))
        self.npStartingPointY.setText(_translate("MainWindow", "1"))
        self.label_6.setText(_translate("MainWindow", "Stop boundary X, Y:"))
        self.label_5.setText(_translate("MainWindow", "Resolution X, Y:"))
        self.label_2.setText(_translate("MainWindow", "Starting point X, Y:"))
        self.npStartingPointX.setText(_translate("MainWindow", "1"))
        self.label_4.setText(_translate("MainWindow", "Start boundary X, Y:"))
        self.label.setText(_translate("MainWindow", "Tolerance"))
        self.npStartBoundaryX.setText(_translate("MainWindow", "-4"))
        self.npStartBoundaryY.setText(_translate("MainWindow", "-4"))
        self.npStopBoundaryX.setText(_translate("MainWindow", "4"))
        self.npStopBoundaryY.setText(_translate("MainWindow", "4"))
        self.npResolutionX.setText(_translate("MainWindow", "0.01"))
        self.npResolutionY.setText(_translate("MainWindow", "0.01"))
        self.npTolerance.setText(_translate("MainWindow", "0.01"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Drawing parameters"))
        self.label_3.setText(_translate("MainWindow", "Start boundary X, Y:"))
        self.dpStartBoundaryX.setText(_translate("MainWindow", "-4"))
        self.dpStartBoundaryY.setText(_translate("MainWindow", "-4"))
        self.label_7.setText(_translate("MainWindow", "Stop boundary X, Y:"))
        self.label_8.setText(_translate("MainWindow", "Resolution X, Y:"))
        self.dpStopBoundaryX.setText(_translate("MainWindow", "4"))
        self.dpStopBoundaryY.setText(_translate("MainWindow", "4"))
        self.dpResolutionX.setText(_translate("MainWindow", "0.5"))
        self.dpResolutionY.setText(_translate("MainWindow", "0.5"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Goal function"))
        self.formulaInput.setText(_translate("MainWindow", "x ^ 4 * (y - 1) ^ 2  + y ^ 4 * (x - 1) ^ 2"))
        self.executeButton.setText(_translate("MainWindow", "Execute"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.resultTab), _translate("MainWindow", "Result"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.consoleTab), _translate("MainWindow", "Console"))

